# Generated by Django 4.2.11 on 2024-04-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_project_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="end_date",
            new_name="deadline",
        ),
    ]
