# Generated by Django 4.2.11 on 2024-04-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_end_date_task_deadline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["project__name", "name"]},
        ),
    ]
