# Generated by Django 5.0.4 on 2024-06-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_task_options_task_parent_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default='2027-12-31'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
